import { User } from '../../api/types/user';

export const registrationRequests: User[] = [
  {
    profilePhotoUrl: 'assets/portrait.jpg',
    firstName: 'Ion',
    lastName: 'Popescu',
    email: 'ion.popescu@example.com',
    department: 'Corporate Bank',
    team: 'Cash Management',
    jobTitle: 'Cash Manager',
    dateOfEmployment: '2019-06-01',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Ana',
    lastName: 'Ionescu',
    email: 'ana.ionescu@example.com',
    department: 'Investment Bank',
    team: 'Equity Capital Markets',
    jobTitle: 'Investment Banking Analyst',
    dateOfEmployment: '2018-02-15',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Mihai',
    lastName: 'Vasilescu',
    email: 'mihai.vasilescu@example.com',
    department: 'Private Bank',
    team: 'Private Wealth Management',
    jobTitle: 'Wealth Manager',
    dateOfEmployment: '2020-09-12',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Elena',
    lastName: 'Dumitrescu',
    email: 'elena.dumitrescu@example.com',
    department: 'Asset Management',
    team: 'Real Estate Investments',
    jobTitle: 'Real Estate Analyst',
    dateOfEmployment: '2016-08-24',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Andrei',
    lastName: 'Marin',
    email: 'andrei.marin@example.com',
    department: 'Wealth Management',
    team: 'Investment Advisory',
    jobTitle: 'Investment Advisor',
    dateOfEmployment: '2022-01-03',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Gabriela',
    lastName: 'Petrovici',
    email: 'gabriela.petrovici@example.com',
    department: 'Global Markets',
    team: 'Equities Trading',
    jobTitle: 'Equity Trader',
    dateOfEmployment: '2017-11-13',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Radu',
    lastName: 'Stefanescu',
    email: 'radu.stefanescu@example.com',
    department: 'Global Transaction Banking',
    team: 'Trade Finance',
    jobTitle: 'Trade Finance Manager',
    dateOfEmployment: '2021-03-29',
    skills: [],
    hobbies: [],
    previousExperience: [],
  },
];

export const users: User[] = [
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Larisa',
    lastName: 'Mihai',
    email: 'larisa.mihai@example.com',
    department: 'Marketing',
    team: 'Brand Development',
    jobTitle: 'Brand Manager',
    dateOfEmployment: '2018-10-12',
    skills: ['Digital Marketing', 'Market Research'],
    hobbies: ['Photography', 'Reading'],
    previousExperience: ['Worked as a Marketing Coordinator at XYZ Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Dan',
    lastName: 'Ionescu',
    email: 'dan.ionescu@example.com',
    department: 'Engineering',
    team: 'Product Engineering',
    jobTitle: 'Mechanical Engineer',
    dateOfEmployment: '2016-06-09',
    skills: ['Mechanical Design', 'CAD'],
    hobbies: ['Hiking', 'Playing Guitar'],
    previousExperience: ['Worked as a Design Engineer at ABC Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Catalina',
    lastName: 'Popescu',
    email: 'catalina.popescu@example.com',
    department: 'Finance',
    team: 'Corporate Accounting',
    jobTitle: 'Accounting Manager',
    dateOfEmployment: '2017-03-21',
    skills: ['Financial Analysis', 'Budgeting'],
    hobbies: ['Cooking', 'Traveling'],
    previousExperience: ['Worked as a Senior Accountant at DEF Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Andrei',
    lastName: 'Constantinescu',
    email: 'andrei.constantinescu@example.com',
    department: 'IT Services',
    team: 'Network Management',
    jobTitle: 'Network Administrator',
    dateOfEmployment: '2019-05-02',
    skills: ['Networking', 'Server Administration'],
    hobbies: ['Gaming', 'Programming'],
    previousExperience: ['Worked as a Systems Administrator at GHI Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Elena',
    lastName: 'Marinescu',
    email: 'elena.marinescu@example.com',
    department: 'Sales',
    team: 'Key Account Management',
    jobTitle: 'Key Account Manager',
    dateOfEmployment: '2021-02-28',
    skills: ['Sales Strategy', 'Negotiation'],
    hobbies: ['Traveling', 'Yoga'],
    previousExperience: ['Worked as a Sales Representative at JKL Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Cosmin',
    lastName: 'Enache',
    email: 'cosmin.enache@example.com',
    department: 'Customer Service',
    team: 'Support Services',
    jobTitle: 'Customer Support Specialist',
    dateOfEmployment: '2020-11-01',
    skills: ['Customer Relationship Management', 'Problem Solving'],
    hobbies: ['Playing Football', 'Listening to Music'],
    previousExperience: ['Worked as a Support Representative at MNO Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Mihaela',
    lastName: 'Pavel',
    email: 'mihaela.pavel@example.com',
    department: 'Human Resources',
    team: 'Employee Relations',
    jobTitle: 'Employee Relations Manager',
    dateOfEmployment: '2018-09-17',
    skills: ['Employee Engagement', 'Conflict Resolution'],
    hobbies: ['Painting', 'Hiking'],
    previousExperience: ['Worked as an HR Specialist at PQR Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Ionut',
    lastName: 'Petrescu',
    email: 'ionut.petrescu@example.com',
    department: 'Supply Chain',
    team: 'Logistics',
    jobTitle: 'Logistics Coordinator',
    dateOfEmployment: '2017-04-05',
    skills: ['Inventory Management', 'Supply Chain Optimization'],
    hobbies: ['Cooking', 'Playing Basketball'],
    previousExperience: ['Worked as a Warehouse Supervisor at STU Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Madalina',
    lastName: 'Vasile',
    email: 'madalina.vasile@example.com',
    department: 'Legal',
    team: 'Contract Law',
    jobTitle: 'Legal Counsel',
    dateOfEmployment: '2016-03-11',
    skills: ['Contract Drafting', 'Legal Research'],
    hobbies: ['Reading', 'Playing Tennis'],
    previousExperience: ['Worked as a Paralegal at VWX Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Cristian',
    lastName: 'Dumitru',
    email: 'cristian.dumitru@example.com',
    department: 'Research and Development',
    team: 'Innovation Team',
    jobTitle: 'Research Scientist',
    dateOfEmployment: '2019-01-07',
    skills: ['Data Analysis', 'Experiment Design'],
    hobbies: ['Photography', 'Cooking'],
    previousExperience: ['Worked as a Research Assistant at YZA Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Sorina',
    lastName: 'Gheorghe',
    email: 'sorina.gheorghe@example.com',
    department: 'Product Management',
    team: 'Product Strategy',
    jobTitle: 'Product Manager',
    dateOfEmployment: '2019-09-22',
    skills: ['Product Lifecycle Management', 'Market Research'],
    hobbies: ['Gardening', 'Reading'],
    previousExperience: [
      'Worked as an Assistant Product Manager at ABC Company',
    ],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Alexandru',
    lastName: 'Stan',
    email: 'alexandru.stan@example.com',
    department: 'IT Services',
    team: 'Software Engineering',
    jobTitle: 'Software Developer',
    dateOfEmployment: '2020-02-14',
    skills: ['Web Development', 'Database Management'],
    hobbies: ['Gaming', 'Playing Guitar'],
    previousExperience: [
      'Worked as a Junior Software Developer at DEF Company',
    ],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Anamaria',
    lastName: 'Dragomir',
    email: 'anamaria.dragomir@example.com',
    department: 'Quality Assurance',
    team: 'Testing',
    jobTitle: 'QA Tester',
    dateOfEmployment: '2017-06-28',
    skills: ['Manual Testing', 'Test Automation'],
    hobbies: ['Photography', 'Watching Movies'],
    previousExperience: ['Worked as a Software Tester at GHI Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Gabriel',
    lastName: 'Ionita',
    email: 'gabriel.ionita@example.com',
    department: 'Operations',
    team: 'Process Improvement',
    jobTitle: 'Operations Analyst',
    dateOfEmployment: '2021-11-03',
    skills: ['Process Optimization', 'Data Analysis'],
    hobbies: ['Swimming', 'Playing Chess'],
    previousExperience: ['Worked as a Business Analyst at JKL Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Daniela',
    lastName: 'Anton',
    email: 'daniela.anton@example.com',
    department: 'Finance',
    team: 'Budgeting and Forecasting',
    jobTitle: 'Financial Analyst',
    dateOfEmployment: '2018-04-19',
    skills: ['Financial Modeling', 'Risk Analysis'],
    hobbies: ['Running', 'Painting'],
    previousExperience: ['Worked as a Financial Consultant at MNO Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Razvan',
    lastName: 'Stoica',
    email: 'razvan.stoica@example.com',
    department: 'Marketing',
    team: 'Digital Marketing',
    jobTitle: 'Digital Marketing Specialist',
    dateOfEmployment: '2022-01-16',
    skills: ['Social Media Marketing', 'SEO'],
    hobbies: ['Writing', 'Playing Tennis'],
    previousExperience: ['Worked as a Marketing Assistant at PQR Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Ioana',
    lastName: 'Pop',
    email: 'ioana.pop@example.com',
    department: 'Customer Service',
    team: 'Customer Retention',
    jobTitle: 'Customer Retention Specialist',
    dateOfEmployment: '2016-07-05',
    skills: ['Customer Relationship Management', 'Problem Solving'],
    hobbies: ['Photography', 'Traveling'],
    previousExperience: [
      'Worked as a Customer Support Representative at STU Company',
    ],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Marius',
    lastName: 'Preda',
    email: 'marius.preda@example.com',
    department: 'Sales',
    team: 'Field Sales',
    jobTitle: 'Field Sales Representative',
    dateOfEmployment: '2019-12-03',
    skills: ['Sales Strategy', 'Relationship Building'],
    hobbies: ['Playing Football', 'Cooking'],
    previousExperience: ['Worked as a Sales Intern at VWX Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Camelia',
    lastName: 'Ionescu',
    email: 'camelia.ionescu@example.com',
    department: 'Human Resources',
    team: 'Training and Development',
    jobTitle: 'Training Coordinator',
    dateOfEmployment: '2017-03-15',
    skills: ['Training Needs Analysis', 'Learning Management Systems'],
    hobbies: ['Yoga', 'Reading'],
    previousExperience: ['Worked as a Training Assistant at YZA Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Florin',
    lastName: 'Radulescu',
    email: 'florin.radulescu@example.com',
    department: 'Data Analytics',
    team: 'Data Management',
    jobTitle: 'Data Analyst',
    dateOfEmployment: '2021-09-20',
    skills: ['Data Visualization', 'Statistical Analysis'],
    hobbies: ['Playing Chess', 'Listening to Music'],
    previousExperience: ['Worked as a Data Entry Clerk at ABC Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Camelia',
    lastName: 'Dinu',
    email: 'camelia.dinu@example.com',
    department: 'Risk Management',
    team: 'Credit Risk',
    jobTitle: 'Credit Risk Analyst',
    dateOfEmployment: '2018-07-02',
    skills: ['Credit Analysis', 'Risk Modeling'],
    hobbies: ['Painting', 'Hiking'],
    previousExperience: ['Worked as a Risk Management Intern at DEF Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Cristian',
    lastName: 'Tudose',
    email: 'cristian.tudose@example.com',
    department: 'Information Technology',
    team: 'Software Development',
    jobTitle: 'Software Engineer',
    dateOfEmployment: '2021-04-21',
    skills: ['Software Development', 'Agile Methodologies'],
    hobbies: ['Gaming', 'Playing Guitar'],
    previousExperience: [
      'Worked as a Junior Software Developer at GHI Company',
    ],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Iulia',
    lastName: 'Georgescu',
    email: 'iulia.georgescu@example.com',
    department: 'Human Resources',
    team: 'Recruitment',
    jobTitle: 'Recruiter',
    dateOfEmployment: '2019-10-14',
    skills: ['Talent Acquisition', 'Interviewing'],
    hobbies: ['Traveling', 'Photography'],
    previousExperience: ['Worked as an HR Assistant at JKL Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Bogdan',
    lastName: 'Popa',
    email: 'bogdan.popa@example.com',
    department: 'Finance',
    team: 'Financial Reporting',
    jobTitle: 'Financial Analyst',
    dateOfEmployment: '2017-04-15',
    skills: ['Financial Analysis', 'Financial Modeling'],
    hobbies: ['Playing Football', 'Reading'],
    previousExperience: ['Worked as a Financial Intern at MNO Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Diana',
    lastName: 'Ciobanu',
    email: 'diana.ciobanu@example.com',
    department: 'Audit',
    team: 'Internal Audit',
    jobTitle: 'Internal Auditor',
    dateOfEmployment: '2016-09-01',
    skills: ['Risk Assessment', 'Internal Controls'],
    hobbies: ['Cooking', 'Hiking'],
    previousExperience: ['Worked as an Audit Assistant at PQR Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Vasile',
    lastName: 'Mocanu',
    email: 'vasile.mocanu@example.com',
    department: 'Corporate Communications',
    team: 'Public Relations',
    jobTitle: 'PR Specialist',
    dateOfEmployment: '2020-05-23',
    skills: ['Media Relations', 'Press Release Writing'],
    hobbies: ['Photography', 'Playing Guitar'],
    previousExperience: ['Worked as a PR Assistant at STU Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Alina',
    lastName: 'Dragomir',
    email: 'alina.dragomir@example.com',
    department: 'Government & Regulatory Affairs',
    team: 'Government Relations',
    jobTitle: 'Government Relations Specialist',
    dateOfEmployment: '2018-11-29',
    skills: ['Public Policy', 'Legislative Affairs'],
    hobbies: ['Reading', 'Painting'],
    previousExperience: [
      'Worked as a Government Relations Intern at VWX Company',
    ],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Florin',
    lastName: 'Antonescu',
    email: 'florin.antonescu@example.com',
    department: 'Research',
    team: 'Equity Research',
    jobTitle: 'Equity Research Analyst',
    dateOfEmployment: '2019-02-11',
    skills: ['Financial Modeling', 'Equity Valuation'],
    hobbies: ['Playing Tennis', 'Cooking'],
    previousExperience: ['Worked as a Research Intern at YZA Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Ioana',
    lastName: 'Nicolae',
    email: 'ioana.nicolae@example.com',
    department: 'Strategy and Business Development',
    team: 'Corporate Strategy',
    jobTitle: 'Strategy Analyst',
    dateOfEmployment: '2022-06-01',
    skills: ['Market Analysis', 'Strategic Planning'],
    hobbies: ['Traveling', 'Playing Piano'],
    previousExperience: ['Worked as a Business Strategy Intern at ABC Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Adrian',
    lastName: 'Ilie',
    email: 'adrian.ilie@example.com',
    department: 'Real Estate Management',
    team: 'Property Management',
    jobTitle: 'Property Manager',
    dateOfEmployment: '2015-03-08',
    skills: ['Property Leasing', 'Facilities Management'],
    hobbies: ['Playing Football', 'Listening to Music'],
    previousExperience: [
      'Worked as an Assistant Property Manager at DEF Company',
    ],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Simona',
    lastName: 'Constantin',
    email: 'simona.constantin@example.com',
    department: 'Legal',
    team: 'Corporate Governance',
    jobTitle: 'Corporate Governance Analyst',
    dateOfEmployment: '2021-08-15',
    skills: ['Legal Compliance', 'Board Governance'],
    hobbies: ['Reading', 'Yoga'],
    previousExperience: ['Worked as a Legal Intern at GHI Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Marius',
    lastName: 'Dumitrache',
    email: 'marius.dumitrache@example.com',
    department: 'Compliance',
    team: 'Regulatory Compliance',
    jobTitle: 'Compliance Officer',
    dateOfEmployment: '2017-12-04',
    skills: ['Risk Assessment', 'Compliance Auditing'],
    hobbies: ['Playing Tennis', 'Cooking'],
    previousExperience: ['Worked as a Compliance Specialist at JKL Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Oana',
    lastName: 'Pavel',
    email: 'oana.pavel@example.com',
    department: 'Operations',
    team: 'Client Services',
    jobTitle: 'Client Services Associate',
    dateOfEmployment: '2020-07-20',
    skills: ['Client Relationship Management', 'Problem Solving'],
    hobbies: ['Traveling', 'Photography'],
    previousExperience: [
      'Worked as a Client Support Specialist at MNO Company',
    ],
  },
];

export const inactiveUsers: User[] = [
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Stefan',
    lastName: 'Popovici',
    email: 'stefan.popovici@example.com',
    department: 'Sales',
    team: 'Inside Sales',
    jobTitle: 'Inside Sales Representative',
    dateOfEmployment: '2022-03-10',
    skills: ['Sales Prospecting', 'Cold Calling'],
    hobbies: ['Playing Football', 'Listening to Music'],
    previousExperience: ['Worked as a Sales Intern at XYZ Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Ana',
    lastName: 'Munteanu',
    email: 'ana.munteanu@example.com',
    department: 'Marketing',
    team: 'Content Marketing',
    jobTitle: 'Content Marketing Specialist',
    dateOfEmployment: '2021-07-15',
    skills: ['Content Creation', 'SEO'],
    hobbies: ['Writing', 'Reading'],
    previousExperience: ['Worked as a Marketing Assistant at ABC Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Radu',
    lastName: 'Stancu',
    email: 'radu.stancu@example.com',
    department: 'Finance',
    team: 'Financial Planning',
    jobTitle: 'Financial Analyst',
    dateOfEmployment: '2020-09-08',
    skills: ['Financial Modeling', 'Budgeting'],
    hobbies: ['Playing Tennis', 'Cooking'],
    previousExperience: ['Worked as a Finance Intern at DEF Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Elena',
    lastName: 'Popovici',
    email: 'elena.popovici@example.com',
    department: 'IT Services',
    team: 'Database Administration',
    jobTitle: 'Database Administrator',
    dateOfEmployment: '2019-11-25',
    skills: ['Database Management', 'SQL'],
    hobbies: ['Gaming', 'Painting'],
    previousExperience: ['Worked as a Database Developer at GHI Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Andreea',
    lastName: 'Radu',
    email: 'andreea.radu@example.com',
    department: 'Customer Service',
    team: 'Technical Support',
    jobTitle: 'Technical Support Specialist',
    dateOfEmployment: '2022-02-02',
    skills: ['Troubleshooting', 'Customer Assistance'],
    hobbies: ['Traveling', 'Photography'],
    previousExperience: ['Worked as a Help Desk Technician at JKL Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Mihai',
    lastName: 'Gavril',
    email: 'mihai.gavril@example.com',
    department: 'Human Resources',
    team: 'Compensation and Benefits',
    jobTitle: 'Compensation Analyst',
    dateOfEmployment: '2020-10-30',
    skills: ['Salary Benchmarking', 'Job Evaluation'],
    hobbies: ['Playing Guitar', 'Hiking'],
    previousExperience: ['Worked as an HR Assistant at MNO Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Raluca',
    lastName: 'Stoian',
    email: 'raluca.stoian@example.com',
    department: 'Operations',
    team: 'Supply Chain Management',
    jobTitle: 'Supply Chain Analyst',
    dateOfEmployment: '2021-01-05',
    skills: ['Supply Chain Planning', 'Inventory Optimization'],
    hobbies: ['Reading', 'Playing Tennis'],
    previousExperience: ['Worked as a Logistics Coordinator at PQR Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Mircea',
    lastName: 'Diaconu',
    email: 'mircea.diaconu@example.com',
    department: 'Research and Development',
    team: 'Product Innovation',
    jobTitle: 'Product Designer',
    dateOfEmployment: '2019-08-18',
    skills: ['UI/UX Design', 'Prototyping'],
    hobbies: ['Drawing', 'Playing Piano'],
    previousExperience: ['Worked as a UX Designer at STU Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'Cristina',
    lastName: 'Predescu',
    email: 'cristina.predescu@example.com',
    department: 'Sales',
    team: 'Sales Operations',
    jobTitle: 'Sales Operations Analyst',
    dateOfEmployment: '2022-04-12',
    skills: ['Sales Analytics', 'Salesforce CRM'],
    hobbies: ['Cooking', 'Listening to Music'],
    previousExperience: ['Worked as a Sales Support Specialist at VWX Company'],
  },
  {
    profilePhotoUrl: 'assets/profile-photo-placeholder.png',
    firstName: 'George',
    lastName: 'Iacob',
    email: 'george.iacob@example.com',
    department: 'IT Services',
    team: 'Cybersecurity',
    jobTitle: 'Cybersecurity Analyst',
    dateOfEmployment: '2020-06-17',
    skills: ['Network Security', 'Incident Response'],
    hobbies: ['Gaming', 'Watching Movies'],
    previousExperience: ['Worked as a Security Administrator at YZA Company'],
  },
];
